### ISSUE TITLE
Download link?

### ISSUE THREAD

**Issue by bw4sz** [FrankFeng-23/SPREAD#1]
This repo looks really interesting. Can you explain the intended download mechanism?

Clicking on download leads to
<img width="1792" alt="Screenshot 2024-10-17 at 10 50 40 AM" src="https://github.com/user-attachments/assets/8ed1fb7e-30af-4ab0-912c-2c836369e704">

<img width="1629" alt="Screenshot 2024-10-17 at 10 50 46 AM" src="https://github.com/user-attachments/assets/9136da51-8006-4f20-8469-0c2b5046fdc1">

**Comment by FrankFeng-23** [comment]
Thanks for reaching out! Most of the SPREAD's work was done in China, so I uploaded the data to a Chinese cloud provider (I tried zenodo, but the upload speed was too slow). I've just arrived in the UK recently and I'm planning on uploading it to google drive or somewhere else these days.

**Comment by bw4sz** [comment]
Thanks, i'm happy to help, how large is it?

**Comment by FrankFeng-23** [comment]
For the ground-level dataset, the size is ~40GB. Appreciate your willingness to help, but by the end of the week, I should be able to upload the data on Zenodo or Google Drive.

**Comment by bw4sz** [comment]
Great, we upload large datasets there as well https://zenodo.org/records/10926344

Looking forward to exploring the airborne perspective of the dataset.

**Comment by FrankFeng-23** [comment]
We've uploaded our dataset on Zenodo. The link has been updated.

**Comment by bw4sz** [comment]
Thank you, I’ll look at it Monday

Ben Weinstein, Ph.D.
Research Scientist
University of Florida
