### ISSUE TITLE
Too many different instances in Birch Forest (and only there)

### ISSUE THREAD

**Issue by 4ndr3aR** [FrankFeng-23/SPREAD#2]
Hey there! First of all: great dataset, congrats!

I'm trying to do some instance segmentation but I noticed that the Birch Forest has up to 2522 different instances on some images.

![image](https://github.com/user-attachments/assets/94ca704a-ff48-42f9-9a5b-bc823dd4522b)

I've seen that the other scenes don't have this problem, probably you just forgot to "cut" the instances to 256, correct?

![image](https://github.com/user-attachments/assets/fb630694-7820-4ea9-9f17-d38f0268bcad)

So I was wondering what the correct approach to use the Birch Forest with other scenes could be. Probably it's sufficient to just extract the unique classes with numpy and have the frequencies returned as well, cutting the array to 256. After that, one can copy to a new image only the pixels that correspond to one of the 256 most frequent colors. Does this make sense or is there a much easier way?

Thanks!

**Comment by FrankFeng-23** [comment]
Hi, thanks for reaching out! In fact, I have encountered similar situations before. I suspect this might be related to some APIs of AirSim, the simulator we use for collecting labeled data. However, I previously resolved it in the following way:
First, you should be able to find a _color_palette.xlsx_ file on Zenodo. This file contains information about up to 255 RGB values within the scene. You can read the RGB information as follows:
```
color_palette_path = "color_palette.xlsx"
color_palette = pd.read_excel(color_palette_path)  # 4 cols: Index, R, G, B
# take RGB
color_palette = color_palette.iloc[:, 1:].values
# to list
valid_rgb_values = color_palette.tolist()
```
Then, you can filter out the pixel that are not in valid_rgb_values, which will give you a very clean labeled image containing at most 255 RGB values. I hope this helps!

**Comment by 4ndr3aR** [comment]
You're right, totally forgot about that file... I'll try, thanks!
